version: "3"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
  drupal:
    build:
      context: .
      dockerfile: ./.docker/php8/Dockerfile
    container_name: drupal
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./drupal-data:/var/www/html
  webserver:
    image: nginx:1.17.4-alpine
    container_name: webserver
    depends_on:
      - drupal
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./drupal-data:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt

volumes:
  db-data:
  certbot-etc:
